"""Add Employee model and assigned_to_employee_id to Device

Revision ID: 768d194fbe56
Revises: 
Create Date: 2025-10-28 10:01:35.568301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768d194fbe56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_employee_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_assigned_to_employee_id'), ['assigned_to_employee_id'], unique=False)
        batch_op.create_foreign_key('fk_device_assigned_to_employee', 'employee', ['assigned_to_employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint('fk_device_assigned_to_employee', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_device_assigned_to_employee_id'))
        batch_op.drop_column('assigned_to_employee_id')

    # ### end Alembic commands ###
